<?php

namespace AppBundle\Repository;

/**
 * RippleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RippleRepository extends \Doctrine\ORM\EntityRepository
{
}
